blank_issues_enabled: true
contact_links:
  - name: 在TONEX QQ群中讨论反馈/建议
    url: https://qm.qq.com/q/H6CUlGKCYi
    about: 您在群内提出可能不会被受理。
  - name: 私聊QingFeng
    url: https://qm.qq.com/q/3d9mY78PoQ
    about: 事实上QingFeng不喜欢被别人打扰,建议您只发起临时会话而不是添加好友。
